name: "Default Workflow (Main)"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format-check:
    uses: ./.github/workflows/black-fmt-check.yml
  linting-check:
    uses: ./.github/workflows/pylint-check.yml
  terraform-apply:
    needs:
      - format-check
      - linting-check
    uses: ./.github/workflows/terraform-apply.yml
    permissions:
      contents: read
    secrets: inherit
