name: "Pylint Check - Python"

on:
  workflow_call:

jobs:
  pylint_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 # This action sets up Python

      - name: Install Dependencies
        run: pip install -r serverless-src/requirements.txt # Install your Python dependencies

      - name: Lint Check
        run: pylint serverless-src/ --disable import-error
